config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login" => "sessions#new"

  get "/hifive/unique" => "hifives#unique"

  resource  :session, only: [:create, :destroy]

  resources :users

  resources :hifives

end

app/models/hifive.rb
class Hifive < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :hifives

    def fullname
      "Mr"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authenticate, :log_out!
  include ApplicationHelper
  include SessionHelper
end

app/controllers/hifives_controller.rb
class HifivesController < ApplicationController
# GET /hifives
  def index
    @hifives = Hifive.all
  end


  def show
  end

  def new
    @user_id = session[:user_id]
    @hifive = Hifive.new
    render :new, :layout => false
  end

  def unique
    @hifive = Hifive.new
  end

  def edit
    @hifive = Hifive.find(params[:id])
  end

  def create
    Hifive.create(hifive_params)
    hi5(hifive_params["phone"], hifive_params["from"], hifive_params["message"])
    redirect_to user_path(session[:user_id])
  end



  private
  def hifive_params
    params.require(:hifive).permit(
      :user_id,
      :to,
      :from,
      :phone,
      :message
      )
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to(user_path(user))
    else
      flash[:error] = "Incorrect username or password."
      redirect_to(login_path)
    end
  end

  def destroy
    log_out!
    redirect_to(login_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate,            except: [:new, :create]
  # before_action :load_user,               except: [:index, :new, :create]
  # before_action :authorize_admin_only,    only:   :index
  # before_action :authorize_user_only,     only:   :show
  # before_action :authorize_user_or_admin, except: [:index, :show, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users    = User.where.not(id: params[:id])
    @user     = User.find(params[:id])
    @hifives  = Hifive.where(phone: @user.phone)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    # if user_params[:password] != user_params[:password_confirmation]
    #   redirect_to(login_path)
    # else
    #   @user = User.create(user_params)
    #   redirect_to(root_path)
    # end
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      @user = User.find(params[:id])
      @user.update(user_params)
      redirect_to(user_path(session[:user_id]))
    # respond_to do |format|
    #   if @user.update(user_params)
    #     format.html { redirect_to @user, notice: 'User was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @user }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :user,
        :phone,
        :image,
        :password,
        :password_confirmation
        )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # def index
  #   @chapters = Chapter.where(saga_id: nil)
  #   if session[:user_id]
  #     user = User.find_by(id: session[:user_id])
  #     redirect_to(user_path(user))
  #   # else
  #   #   redirect_to (login_path)
  #   end
  # end

  def index
    redirect_to(login_path)
  end
end

app/helpers/application_helper.rb
 module ApplicationHelper
  def hi5(phone, name, message)
    account_sid = ENV["TWILIO_API_ID"]
    auth_token = ENV["TWILIO_API_KEY"]
    client = Twilio::REST::Client.new account_sid, auth_token

    from = ENV["TWILIO_PHONE_NUMBER"] # Your Twilio number

    friends = {
    phone => "#{name}",
    }
    friends.each do |key, value|
      client.account.messages.create(
      :from => from,
      :to => key,
      :body => "#{name} has just sent you a Hi 5ive for " + "#{message}"
      )
      puts "Sent message to #{name}"
    end
  end
end

app/helpers/hifives_helper.rb
module HifivesHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def authenticate
    redirect_to login_path unless logged_in?
  end

  def log_out!
    session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hifives/_form.html.erb
<%= form_for(@hifive) do |f| %>

  <div class="hi5-form">
    <div class="field">
      <%= f.label :recipient %><br>
      <%=f.text_field :to %><br>
    </div>
    <div class="field">
      <%= f.label :from %><br>
      <%=f.text_field :from %><br>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%=f.text_field :phone %><br>
    </div>
    <div class="field">
      <%= f.label :message %><br>
      <%=f.text_field :message %><br>
    </div>
    <div class="field">
    <%= f.hidden_field(:user_id, :value => @user_id) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/hifives/edit.html.erb
edit.html.erb

app/views/hifives/index.html.erb
index.html.erb

app/views/hifives/new.html.erb
<%= form_for(@hifive) do |f| %>

  <div class="hi5-form">
    <div class="field">
      <%= f.label :hi5ive_Recipient %><br>
      <%=f.text_field :to, class: "form-styling" %><br>
    </div>
    <div class="field">
      <%= f.label :from %><br>
      <%=f.text_field :from, class: "form-styling"%><br>
    </div>
    <div class="field">
      <%= f.hidden_field(:phone)%>
    </div>
    <div class="field">
      <%= f.label :message %><br>
      <%=f.text_field :message, class: "form-styling", :placeholder => "message" %><br>
    </div>
    <div class="field">
    <%= f.hidden_field(:user_id, :value => @user_id) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/hifives/unique.html.erb
<%= form_for(@hifive) do |f| %>

  <div class="hi5-form">
    <div class="field">
      <%=f.text_field :to, class: "form-styling", :placeholder => "recipient" %><br>
    </div>
    <div class="field">
      <%=f.text_field :from, class: "form-styling", :placeholder => "from"  %><br>
    </div>
    <div class="field">
      <%=f.text_field :phone, class: "form-styling", :placeholder => "phone"  %><br>
    </div>
    <div class="field">
      <%=f.text_field :message, class: "form-styling", :placeholder => "message"  %><br>
    </div>
    <div class="field">
    <%= f.hidden_field(:user_id, :value => @user_id) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hifiveapp</title>
    <!-- Latest compiled and minified JavaScript -->
  <link href='https://fonts.googleapis.com/css?family=Lato:100,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <link rel="shortcut icon" href="../../favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'sessionstyle' %>
  <%= stylesheet_link_tag    'users' %>

  <!-- Google Analytics -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXXX-Y', 'auto');
  ga('send', 'pageview');

  </script>
  <!-- End Google Analytics -->

  <!-- Latest compiled and minified CSS -->
  <!-- Optional theme -->
  <!-- Logo Font -->
</head>
<body>
    <ul class="nav pull-left navbar-inverse navbar-nav navbar-fixed-top">
      <% if session[:user_id] %>
        <li class="login"><%= link_to 'Hi 5ive', user_path(session[:user_id]), class: 'logo' %></li>
      <% else %>
        <li class="login"><%= link_to 'Hi 5ive', login_path, class: 'logo' %></li>
      <% end %>

      <% if session[:user_id] %>
        <li class="login"><%= link_to 'Logout', session_path, method: :delete %></li>
        <% else %>
      <li class="login"><%= link_to 'Log In', login_path %></li>
        <li class="signup"><%= link_to 'Sign Up', new_user_path %></li>
      <% end %>
    </ul>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%=f.text_field :name %><br>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%=f.text_field :email %><br>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%=f.text_field :user %><br>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%=f.text_field :phone %><br>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%=f.text_field :image %><br>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%=f.text_field :password %><br>
  </div>
  <div class="field">
    <%= f.label :Confirm_Password %><br>
    <%=f.text_field :password_confirmation %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
</br><h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= link_to 'New User', new_user_path %>
  <tbody>
    <div class="all-user">
      <% @users.each do |user| %>
        <span>
          <h1><%= user.name %></h1>
          <%= link_to 'Show', user %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      <% end %>
    </div>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<section class="new-user-container">
  <h1>New user</h1>
  <%= render 'form' %>
  <%= link_to 'Back', users_path %>
</section>

app/views/users/show.html.erb
  <div class="main-container">

    <div class="container top50">
        <div class="row profile">
          <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 profile-photo">
                <div class="item-1">
                  <div class="img-container">
                      <a href="#"><img src=<%= @user.image %> alt="" height= "200" width="200"/></a>
                    </div>
                    <div class="robin-key">
                      <p><%= @user.name %></p>

                        <ul>
                          <li title="Email"><a href="mailto:<%= @user.email %>"><i class="glyphicon glyphicon-envelope"></i></a></li>
                            <li title="Edit"><a href=<%= edit_user_path(@user)%>><i class="glyphicon glyphicon-pencil"></i></a></li>
                        </ul>
                    </div>

                    <ul class="follow-list">
                      <li><a href="#"><i class="fa fa-heart"></i> <%= @hifives.length %> </a></li>
                      <li><a href="#"><i class="fa fa-users"></i> <%= @users.length %> </a></li>
                      <li><a href="#"><i class="fa fa-building-o"></i> 80</a></li>
                      <li><a href="#"><i class="fa fa-comments"></i> 120</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            </div>
        </div>
    </div>


  <div class="row clearfix hi5-content">
    <div class="all-users">
      <h1 class="main-heading">WDI August - 2014</h1><button type="button" id="new-hi5-form">Send New Hi 5ive</button>
      <% @users.each do |user| %>
      <div class="user-buttons">
        <span>
          <p><%= user.name %></p>
          <button type="button" class="btn btn-default btn-lg send-hi5" data-user-id="<%= user.id %>" data-user-phone="<%= user.phone %>" data-user-name="<%= user.name %>" data-my-name="<%= @user.name %>"><span class="glyphicon glyphicon-thumbs-up"></span></button>
            <span>
              Hi-5ives: <%= Hifive.where(phone: User.find_by(id: user.id).phone).length %>
            </span>
        </span>
      </div>
      <% end %>
    </div>

    <div id="new-form">
    </div>

      <div class="hi-fives">
        <h1 class="main-heading">Unique Hi 5s this Week: <%= @hifives.length %></h1>
          <% @hifives.each do |hifive| %>
            <div class="each-hi5">
              <span>
                <p class="hi5s">
                  <%= hifive.from %> - <%= hifive.message %>
                </p>
              </span>
            </div>
          <% end %>
      </div>
    </br>
  </div>
</div>


    <script>
      $(document).ready(users.show)
    </script>

app/views/welcome/index.html.erb
<h1>Welcome Page</h1>
<ul>
  <li>Log in Box</li>
  <li>Create new User</li>
  <li>Parallax Feature</li>
</ul>